### ISSUE TITLE
Query fails while node tries to login to skoda services

### ISSUE THREAD

**Issue by MartinGris** [MartinGris/node-red-contrib-skoda-connect#2]
Querying of skoda information fails every time with a error message while the node is trying to log in to skoda services:

TypeError: Cannot read property 'split' of undefined
    at Request._callback (/home/pi/.node-red/node_modules/node-red-contrib-skoda-connect/lib/skoda-library.js:320:105)
    at Request.self.callback (/home/pi/.node-red/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (/home/pi/.node-red/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:314:20)
    at IncomingMessage.<anonymous> (/home/pi/.node-red/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by MartinGris** [comment]
Happens because new terms of use need to be accepted on skoda-connect.com. Login to skoda-connect.com normally and accept the terms of use. After this everything should work fine
