### ISSUE TITLE
Skoda Enyaq iV not working

### ISSUE THREAD

**Issue by foorschtbar** [MartinGris/node-red-contrib-skoda-connect#6]
Hey, i got this two erros with my Enyaq iV:

`"TypeError: Cannot read property 'vehicle' of null"`

`"Not able to find vehicle, did you choose the correct type?."`

**Comment by MartinGris** [comment]
Hi. 
Do you have a detailed exception with the line of code out of the nodered log?

With this information I just can guess. Is your car shown in the MySkoda app?

**Comment by foorschtbar** [comment]
How stupid of me, of course you need the nodered log, sorry for that.

Yes the Skoda Connect Website and MySkoda App works. tronity.io also.

```
nodered     | getVehicles
nodered     | 6 Oct 12:04:22 - [error] [skoda-get:Skoda Connect] Not able to find vehicle, did you choose the correct type?.
nodered     | 6 Oct 12:04:22 - [error] [skoda-get:Skoda Connect] TypeError: Cannot read property 'vehicle' of null
nodered     | TypeError: Cannot read property 'vehicle' of null
nodered     |     at Request._callback (/data/node_modules/node-red-contrib-skoda-connect/lib/skoda-library.js:883:60)
nodered     |     at Request.self.callback (/data/node_modules/request/request.js:185:22)
nodered     |     at Request.emit (events.js:400:28)
nodered     |     at Request.<anonymous> (/data/node_modules/request/request.js:1154:10)
nodered     |     at Request.emit (events.js:400:28)
nodered     |     at Gunzip.<anonymous> (/data/node_modules/request/request.js:1076:12)
nodered     |     at Object.onceWrapper (events.js:519:28)
nodered     |     at Gunzip.emit (events.js:400:28)
nodered     |     at endReadableNT (internal/streams/readable.js:1317:12)
nodered     |     at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

**Comment by MartinGris** [comment]
Thanks.
The request for getting all VINs of the cars in your Skoda account returns an empty list. The error handling in this case is bad, sorry.

The node is working fine for me so there must be something different in your case. This make it hard to find the issue.
 
I will so my best

**Comment by foorschtbar** [comment]
Is there anything i could do to help u?

**Comment by MartinGris** [comment]
you can uncomment the line 881 in lib\skoda-library.js: "console.log(JSON.stringify(body))"

Restart node red and send me what is written to the console

**Comment by foorschtbar** [comment]
```
nodered     | parseEmailForm
nodered     | parsePasswordForm
nodered     | Error: Invalid protocol: skodaconnect:
nodered     |     at Request.init (/data/node_modules/request/request.js:458:31)
nodered     |     at Redirect.onResponse (/data/node_modules/request/lib/redirect.js:149:11)
nodered     |     at Request.onRequestResponse (/data/node_modules/request/request.js:986:22)
nodered     |     at ClientRequest.emit (events.js:400:28)
nodered     |     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)
nodered     |     at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
nodered     |     at TLSSocket.socketOnData (_http_client.js:515:22)
nodered     |     at TLSSocket.emit (events.js:400:28)
nodered     |     at addChunk (internal/streams/readable.js:290:12)
nodered     |     at readableAddChunk (internal/streams/readable.js:265:9)
nodered     |     at TLSSocket.Readable.push (internal/streams/readable.js:204:10)
nodered     |     at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
nodered     | getPersonalData
nodered     | getVehicles
nodered     | {"userVehicles":null}
nodered     | 7 Oct 20:07:07 - [error] [skoda-get:Skoda Connect] Not able to find vehicle, did you choose the correct type?.
nodered     | 7 Oct 20:07:07 - [error] [skoda-get:Skoda Connect] TypeError: Cannot read property 'vehicle' of null
nodered     | TypeError: Cannot read property 'vehicle' of null
nodered     |     at Request._callback (/data/node_modules/node-red-contrib-skoda-connect/lib/skoda-library.js:883:60)
nodered     |     at Request.self.callback (/data/node_modules/request/request.js:185:22)
nodered     |     at Request.emit (events.js:400:28)
nodered     |     at Request.<anonymous> (/data/node_modules/request/request.js:1154:10)
nodered     |     at Request.emit (events.js:400:28)
nodered     |     at Gunzip.<anonymous> (/data/node_modules/request/request.js:1076:12)
nodered     |     at Object.onceWrapper (events.js:519:28)
nodered     |     at Gunzip.emit (events.js:400:28)
nodered     |     at endReadableNT (internal/streams/readable.js:1317:12)
nodered     |     at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

**Comment by MartinGris** [comment]
Thanks!
There is another known exception before the one you described.
Have you installed the latest version of the node?
At least version 1.2.10?

**Comment by foorschtbar** [comment]
Yes, i was on 1.2.10. Now i updated to 1.2.11 end enabled all debug outputs:

```
nodered     | parseEmailForm
nodered     | parsePasswordForm
nodered     | ""
nodered     | Error: Invalid protocol: skodaconnect:
nodered     |     at Request.init (/data/node_modules/request/request.js:458:31)
nodered     |     at Redirect.onResponse (/data/node_modules/request/lib/redirect.js:149:11)
nodered     |     at Request.onRequestResponse (/data/node_modules/request/request.js:986:22)
nodered     |     at ClientRequest.emit (events.js:400:28)
nodered     |     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)
nodered     |     at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
nodered     |     at TLSSocket.socketOnData (_http_client.js:515:22)
nodered     |     at TLSSocket.emit (events.js:400:28)
nodered     |     at addChunk (internal/streams/readable.js:290:12)
nodered     |     at readableAddChunk (internal/streams/readable.js:265:9)
nodered     |     at TLSSocket.Readable.push (internal/streams/readable.js:204:10)
nodered     |     at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
nodered     | getPersonalData
nodered     | getVehicles
nodered     | 8 Oct 15:43:42 - [error] [skoda-get:Skoda Connect] TypeError: Cannot read property 'vehicle' of null
nodered     | TypeError: Cannot read property 'vehicle' of null
nodered     |     at Request._callback (/data/node_modules/node-red-contrib-skoda-connect/lib/skoda-library.js:882:46)
nodered     |     at Request.self.callback (/data/node_modules/request/request.js:185:22)
nodered     |     at Request.emit (events.js:400:28)
nodered     |     at Request.<anonymous> (/data/node_modules/request/request.js:1154:10)
nodered     |     at Request.emit (events.js:400:28)
nodered     |     at Gunzip.<anonymous> (/data/node_modules/request/request.js:1076:12)
nodered     |     at Object.onceWrapper (events.js:519:28)
nodered     |     at Gunzip.emit (events.js:400:28)
nodered     |     at endReadableNT (internal/streams/readable.js:1317:12)
nodered     |     at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

**Comment by MartinGris** [comment]
Login is working fine so i did some research. Also other projects struggled with the Enyaq and needed to do some special development to support it because there is another API only for the Enyac. 
I will try to develop the support for the Enyaq but in the end I will need some help by you because I don't have an Enyaq.

Would you like to support me by testing my code? I  will create a development branch for it.

**Comment by lourdhd** [comment]
Hi, if I can help I have an enyaq too.

**Comment by foorschtbar** [comment]
> Login is working fine so i did some research. Also other projects struggled with the Enyaq and needed to do some special development to support it because there is another API only for the Enyac. 

Like this project? https://github.com/lendy007/skodaconnect

> Would you like to support me by testing my code? I  will create a development branch for it.

Yes, sure!

**Comment by MartinGris** [comment]
Thanks @lourdhd ! I appreciate that.

> Like this project? https://github.com/lendy007/skodaconnect

Yes, or this one: https://github.com/TA2k/ioBroker.vw-connect

Would it be possible for one of you to give me his credentials? Otherwise the programming and testing would be time consuming. You can send me a message in [Telegram](https://t.me/M4rt1nGr1s001)

**Comment by MartinGris** [comment]
support for enyaq added with version 1.3.0

**Comment by foorschtbar** [comment]
Hey @lourdhd, is your Enyaq still working? i got a "No Login Form found. Please check your E-Mail in the app."

**Comment by MartinGris** [comment]
check the newest version. There was a change in the login mechanism by skoda.
#9

**Comment by foorschtbar** [comment]
Oh sry, I only subscribed for release notifications and didn't see the update
